version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      npm-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: terraform
    directory: /infra
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      terraform-providers:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      docker-images:
        patterns: ["*"]
